name: Build English Version
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
      - name: Change filename
        run: cp main.pdf document_english.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'English'
          path: 'document_english.pdf'